

hash_table: gcc -pthread -o hash_table hash_table.c alloc-functions.c functions.c hash-function.c threading.c
server: gcc -pthread -o server server.c hash_table.c alloc-functions.c functions.c hash-function.c threading.c